#+TITLE: Homebrew Tap for the Marmaduke Chromium builds

If you're looking for a macOS build of the latest stable Chromium
which includes modern video codecs such as H.264, then the marmaduke
builds as advertised on [[https://chromium.woolyss.com/#mac][Woolyss]] are your best bet.

This homebrew tap was created for the easy installation of
above-mentioned builds.

The latest update is v79.0.3945.88 (706915).

To install do:

#+BEGIN_SRC shell
brew tap mtslzr/marmaduke-chromium
brew cask install marmaduke-chromium
#+END_SRC

If you prefer the build without google sync and widevine (which you do
need to play for example Netflix), then rather install:

#+BEGIN_SRC shell
brew cask install marmaduke-chromium-nosync
#+END_SRC

Since 2019-03-05, there is also a cask for the [[https://github.com/Eloston/ungoogled-chromium/blob/master/README.md][UNGOOGLED]] Chromium
build by Marmaduke which you can install with:

#+BEGIN_SRC shell
brew cask install marmaduke-chromium-ungoogled
#+END_SRC

* Which cask should I use?

If you don't know, then use =marmaduke-chromium=.

* Updating your chromium

From here on, do the following to upgrade when a new build becomes
available:

#+BEGIN_SRC shell
brew update
brew cask upgrade marmaduke-chromium
#+END_SRC

My RSS reader keeps on eye on the [[https://github.com/macchrome/macstable/releases][marmaduke releases]], but please [[https://github.com/cpbotha/homebrew-marmaduke-chromium/issues][file
an issue]] here if you notice that we're out of date!

* Important notice re version v70.0.3538.102

If you installed the =marmaduke-chromium= cask of v70.0.3538.102 on
November 11 or 12, you might have received a [[https://github.com/macchrome/macstable/issues/4][temporarily broken
build]]. If your chromium does not want to run, please do the following
to get marmaduke's fixed build:

#+BEGIN_SRC shell
brew update
brew cask uninstall marmaduke-chromium
brew cask install marmaduke-chromium
#+END_SRC
